### ISSUE TITLE
Some additional doc

### ISSUE THREAD

**Issue by AlbertoLopSie** [jiharley/CamCom#1]
Hi jiharley,

I´m interested in this project? Could you give some more info about it?  What´s supposed to be the transmitter endpoint?  

Thanks!
Alberto

**Comment by jiharley** [comment]
@AlbertoLopSie  Sorry that I didn't notice the message until today. The transmitter is modulated LED light using USRP device. Any other part do you want to know?

**Comment by AlbertoLopSie** [comment]
Hi  jiharley !

Thanks for replying!

I would like any info you may give me in order to be able to reproduce the
experience you detail in your paper.  I´m not familiar with USRP, but any
predefined waveform, ARB file or message format you may have woul be very
helpfull.

Thank you very much!

---

Saludos,
  Alberto

Mis direcciones de mail son Alberto2k7@gmail.com o AlbertoLS@me.com.

**Comment by jiharley** [comment]
[PID1152744.pdf](https://github.com/jiharley/CamCom/files/88514/PID1152744.pdf)
@AlbertoLopSie Here is the paper published on VTC which describes my work in detail. Hope it could be helpful. By the way, you can also use SCMs such as c8051 to produce modulated LED light.
